### ISSUE TITLE
 不支持 FreshRSS 的 Fever API

### ISSUE THREAD

**Issue by SeptemberHX** [weekend-project-space/webfollow-app#5]
作者您好！感谢开源了这个工具，想换一个阅读工具好久了，FreshRSS 界面太古老了。

我尝试用官网的版本去添加 freshrss 的 fever api，发现无法添加，看了一下开发者工具，发现请求的网址是 `https://XXXX/api/fever.php?api_key=XXXX&api=1`，翻了一下 freshrss 的[文档](https://freshrss.github.io/FreshRSS/en/developers/06_Fever_API.html)，发现它用的是 `api_version = 3`：

```bash
curl -s -F "api_key=$api_key" 'https://freshrss.example.net/api/fever.php?api'

// This should give:
//{
//	"api_version": 3,
//	"auth": 1,
//	"last_refreshed_on_time": "1520013061"
//}
```

**Comment by weekend-project-space** [comment]
方便提供测试用的地址和账号吗

**Comment by SeptemberHX** [comment]
测试用：
* 地址：https://rss.wow.hxgpark.com/
* 用户名：test
* 密码：test_test

命令行测试如下：
```shell
monotune@feedbin:~$ curl -s -F "api_key=`echo -n "test:test_test" | md5sum | cut -d' ' -f1`" 'https://rss.wow.
hxgpark.com/api/fever.php?api'
{"api_version":3,"auth":1,"last_refreshed_on_time":0}
monotune@feedbin:~$
```

**Comment by weekend-project-space** [comment]
之前需要强制刷新fever 地址才能生效，已调整为不需要强制刷新

现在看了下问题是跨越引起的，需要后端服务器允许该域名 https://webfollow.cc  的请求

**Comment by SeptemberHX** [comment]
感谢，我又试了一下，现在登陆会提示：登录失败。看了一下刚刚修改的代码，应该是返回数据里 auth 为 0导致的：
![image](https://github.com/user-attachments/assets/22e22000-e7fe-4056-be3e-d1aaf54ad6d9)
![image](https://github.com/user-attachments/assets/33405a90-88fe-459a-b734-b74578cbfa06)

将上面的请求直接导入 ApiFox 测试，发现请求依然失败，后将 api_key 放到 Body form-data 后成功：
![image](https://github.com/user-attachments/assets/31615e5c-fa2f-4c52-bda9-5e16c7c95c49)

**Comment by SeptemberHX** [comment]
另外，请问 fever url 支持纯 IPV6 的域名吗，还是上面的这个实例，用 ipv6 域名指向过去，就会弹出下面的错误：
![image](https://github.com/user-attachments/assets/237875f4-b17c-4f50-949f-e2a06568ded4)

我是在容器里跑的 webfollow，在容器里试着用 ping wget 之类的请求 ipv6 地址，是好使的，所以应该不是网络问题

**Comment by weekend-project-space** [comment]
> 另外，请问 fever url 支持纯 IPV6 的域名吗，还是上面的这个实例，用 ipv6 域名指向过去，就会弹出下面的错误： ![image](https://private-user-images.githubusercontent.com/18042424/396398308-237875f4-b17c-4f50-949f-e2a06568ded4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjI3ODgsIm5iZiI6MTczNDQyMjQ4OCwicGF0aCI6Ii8xODA0MjQyNC8zOTYzOTgzMDgtMjM3ODc1ZjQtYjE3Yy00ZjUwLTk0OWYtZTJhMDY1NjhkZWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA4MDEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNzRlMzEwYTFhZjlkZjc3YzcxNmEwMjM1YmFiZWIwY2YzODEyZGVhNTA5MDJkMzU1ZjlmNjhkMGYyMmU4OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p9D9Epi9SgtT3r6WiLOe6M7acAOVtGoarVvRtdadBGY)
> 
> 我是在容器里跑的 webfollow，在容器里试着用 ping wget 之类的请求 ipv6 地址，是好使的，所以应该不是网络问题

需要f12看下控制台的截图

**Comment by SeptemberHX** [comment]
> > 另外，请问 fever url 支持纯 IPV6 的域名吗，还是上面的这个实例，用 ipv6 域名指向过去，就会弹出下面的错误： ![image](https://private-user-images.githubusercontent.com/18042424/396398308-237875f4-b17c-4f50-949f-e2a06568ded4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjI3ODgsIm5iZiI6MTczNDQyMjQ4OCwicGF0aCI6Ii8xODA0MjQyNC8zOTYzOTgzMDgtMjM3ODc1ZjQtYjE3Yy00ZjUwLTk0OWYtZTJhMDY1NjhkZWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA4MDEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNzRlMzEwYTFhZjlkZjc3YzcxNmEwMjM1YmFiZWIwY2YzODEyZGVhNTA5MDJkMzU1ZjlmNjhkMGYyMmU4OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p9D9Epi9SgtT3r6WiLOe6M7acAOVtGoarVvRtdadBGY)
> > 我是在容器里跑的 webfollow，在容器里试着用 ping wget 之类的请求 ipv6 地址，是好使的，所以应该不是网络问题
> 
> 需要f12看下控制台的截图

在控制台看到了，还是 cors 的问题，npm 设置 cors 方式不一样导致没有生效；那只剩下前面那个登录失败的问题了

**Comment by weekend-project-space** [comment]
> > > 另外，请问 fever url 支持纯 IPV6 的域名吗，还是上面的这个实例，用 ipv6 域名指向过去，就会弹出下面的错误： ![image](https://private-user-images.githubusercontent.com/18042424/396398308-237875f4-b17c-4f50-949f-e2a06568ded4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjI3ODgsIm5iZiI6MTczNDQyMjQ4OCwicGF0aCI6Ii8xODA0MjQyNC8zOTYzOTgzMDgtMjM3ODc1ZjQtYjE3Yy00ZjUwLTk0OWYtZTJhMDY1NjhkZWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA4MDEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNzRlMzEwYTFhZjlkZjc3YzcxNmEwMjM1YmFiZWIwY2YzODEyZGVhNTA5MDJkMzU1ZjlmNjhkMGYyMmU4OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p9D9Epi9SgtT3r6WiLOe6M7acAOVtGoarVvRtdadBGY)
> > > 我是在容器里跑的 webfollow，在容器里试着用 ping wget 之类的请求 ipv6 地址，是好使的，所以应该不是网络问题
> > 
> > 
> > 需要f12看下控制台的截图
> 
> 在控制台看到了，还是 cors 的问题，npm 设置 cors 方式不一样导致没有生效；那只剩下前面那个登录失败的问题了

f12 应用本地存储空间 auth 的值改一下 token换成 md5后的的值试一下

**Comment by SeptemberHX** [comment]
> > > > 另外，请问 fever url 支持纯 IPV6 的域名吗，还是上面的这个实例，用 ipv6 域名指向过去，就会弹出下面的错误： ![image](https://private-user-images.githubusercontent.com/18042424/396398308-237875f4-b17c-4f50-949f-e2a06568ded4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjI3ODgsIm5iZiI6MTczNDQyMjQ4OCwicGF0aCI6Ii8xODA0MjQyNC8zOTYzOTgzMDgtMjM3ODc1ZjQtYjE3Yy00ZjUwLTk0OWYtZTJhMDY1NjhkZWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA4MDEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNzRlMzEwYTFhZjlkZjc3YzcxNmEwMjM1YmFiZWIwY2YzODEyZGVhNTA5MDJkMzU1ZjlmNjhkMGYyMmU4OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p9D9Epi9SgtT3r6WiLOe6M7acAOVtGoarVvRtdadBGY)
> > > > 我是在容器里跑的 webfollow，在容器里试着用 ping wget 之类的请求 ipv6 地址，是好使的，所以应该不是网络问题
> > > 
> > > 
> > > 需要f12看下控制台的截图
> > 
> > 
> > 在控制台看到了，还是 cors 的问题，npm 设置 cors 方式不一样导致没有生效；那只剩下前面那个登录失败的问题了
> 
> f12 应用本地存储空间 auth 的值改一下 token换成 md5后的的值试一下

还是不行，抛异常了

![image](https://github.com/user-attachments/assets/e1fe09b0-ef19-4c25-964b-d6b56aa60b0f)


![image](https://github.com/user-attachments/assets/5fd0dc6d-cbd1-47d1-a2f1-54b06df7d776)

**Comment by weekend-project-space** [comment]
现在可以了，针对fever.php的请求方式改为了fromdata的形式，还修复了若干不兼容的问题

**Comment by SeptemberHX** [comment]
感谢，测试了一下，能够正常使用 freshrss 的 fever api 了 👍
